package org.prcode.business.basedomain.resourceUrl.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ResourceUrlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    public ResourceUrlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("resourceUrl.f_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("resourceUrl.f_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("resourceUrl.f_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("resourceUrl.f_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("resourceUrl.f_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("resourceUrl.f_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("resourceUrl.f_id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("resourceUrl.f_id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("resourceUrl.f_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("resourceUrl.f_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("resourceUrl.f_url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("resourceUrl.f_url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("resourceUrl.f_url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("resourceUrl.f_url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("resourceUrl.f_url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("resourceUrl.f_url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("resourceUrl.f_url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("resourceUrl.f_url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("resourceUrl.f_url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("resourceUrl.f_url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlDescIsNull() {
            addCriterion("resourceUrl.f_url_desc is null");
            return (Criteria) this;
        }

        public Criteria andUrlDescIsNotNull() {
            addCriterion("resourceUrl.f_url_desc is not null");
            return (Criteria) this;
        }

        public Criteria andUrlDescEqualTo(String value) {
            addCriterion("resourceUrl.f_url_desc =", value, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andUrlDescNotEqualTo(String value) {
            addCriterion("resourceUrl.f_url_desc <>", value, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andUrlDescGreaterThan(String value) {
            addCriterion("resourceUrl.f_url_desc >", value, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andUrlDescGreaterThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_url_desc >=", value, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andUrlDescLessThan(String value) {
            addCriterion("resourceUrl.f_url_desc <", value, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andUrlDescLessThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_url_desc <=", value, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andUrlDescLike(String value) {
            addCriterion("resourceUrl.f_url_desc like", value, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andUrlDescNotLike(String value) {
            addCriterion("resourceUrl.f_url_desc not like", value, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andUrlDescIn(List<String> values) {
            addCriterion("resourceUrl.f_url_desc in", values, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andUrlDescNotIn(List<String> values) {
            addCriterion("resourceUrl.f_url_desc not in", values, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andUrlDescBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_url_desc between", value1, value2, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andUrlDescNotBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_url_desc not between", value1, value2, "urlDesc");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("resourceUrl.f_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("resourceUrl.f_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(String value) {
            addCriterion("resourceUrl.f_parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(String value) {
            addCriterion("resourceUrl.f_parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(String value) {
            addCriterion("resourceUrl.f_parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(String value) {
            addCriterion("resourceUrl.f_parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLike(String value) {
            addCriterion("resourceUrl.f_parent_id like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotLike(String value) {
            addCriterion("resourceUrl.f_parent_id not like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<String> values) {
            addCriterion("resourceUrl.f_parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<String> values) {
            addCriterion("resourceUrl.f_parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andIsMenuIsNull() {
            addCriterion("resourceUrl.f_is_menu is null");
            return (Criteria) this;
        }

        public Criteria andIsMenuIsNotNull() {
            addCriterion("resourceUrl.f_is_menu is not null");
            return (Criteria) this;
        }

        public Criteria andIsMenuEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_is_menu =", value, "isMenu");
            return (Criteria) this;
        }

        public Criteria andIsMenuNotEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_is_menu <>", value, "isMenu");
            return (Criteria) this;
        }

        public Criteria andIsMenuGreaterThan(Boolean value) {
            addCriterion("resourceUrl.f_is_menu >", value, "isMenu");
            return (Criteria) this;
        }

        public Criteria andIsMenuGreaterThanOrEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_is_menu >=", value, "isMenu");
            return (Criteria) this;
        }

        public Criteria andIsMenuLessThan(Boolean value) {
            addCriterion("resourceUrl.f_is_menu <", value, "isMenu");
            return (Criteria) this;
        }

        public Criteria andIsMenuLessThanOrEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_is_menu <=", value, "isMenu");
            return (Criteria) this;
        }

        public Criteria andIsMenuIn(List<Boolean> values) {
            addCriterion("resourceUrl.f_is_menu in", values, "isMenu");
            return (Criteria) this;
        }

        public Criteria andIsMenuNotIn(List<Boolean> values) {
            addCriterion("resourceUrl.f_is_menu not in", values, "isMenu");
            return (Criteria) this;
        }

        public Criteria andIsMenuBetween(Boolean value1, Boolean value2) {
            addCriterion("resourceUrl.f_is_menu between", value1, value2, "isMenu");
            return (Criteria) this;
        }

        public Criteria andIsMenuNotBetween(Boolean value1, Boolean value2) {
            addCriterion("resourceUrl.f_is_menu not between", value1, value2, "isMenu");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("resourceUrl.f_level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("resourceUrl.f_level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Byte value) {
            addCriterion("resourceUrl.f_level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Byte value) {
            addCriterion("resourceUrl.f_level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Byte value) {
            addCriterion("resourceUrl.f_level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Byte value) {
            addCriterion("resourceUrl.f_level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Byte value) {
            addCriterion("resourceUrl.f_level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Byte value) {
            addCriterion("resourceUrl.f_level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Byte> values) {
            addCriterion("resourceUrl.f_level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Byte> values) {
            addCriterion("resourceUrl.f_level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Byte value1, Byte value2) {
            addCriterion("resourceUrl.f_level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Byte value1, Byte value2) {
            addCriterion("resourceUrl.f_level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNull() {
            addCriterion("resourceUrl.f_system_code is null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNotNull() {
            addCriterion("resourceUrl.f_system_code is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeEqualTo(String value) {
            addCriterion("resourceUrl.f_system_code =", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotEqualTo(String value) {
            addCriterion("resourceUrl.f_system_code <>", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThan(String value) {
            addCriterion("resourceUrl.f_system_code >", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_system_code >=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThan(String value) {
            addCriterion("resourceUrl.f_system_code <", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_system_code <=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLike(String value) {
            addCriterion("resourceUrl.f_system_code like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotLike(String value) {
            addCriterion("resourceUrl.f_system_code not like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIn(List<String> values) {
            addCriterion("resourceUrl.f_system_code in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotIn(List<String> values) {
            addCriterion("resourceUrl.f_system_code not in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_system_code between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_system_code not between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfIsNull() {
            addCriterion("resourceUrl.f_need_csrf is null");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfIsNotNull() {
            addCriterion("resourceUrl.f_need_csrf is not null");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_need_csrf =", value, "needCsrf");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfNotEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_need_csrf <>", value, "needCsrf");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfGreaterThan(Boolean value) {
            addCriterion("resourceUrl.f_need_csrf >", value, "needCsrf");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfGreaterThanOrEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_need_csrf >=", value, "needCsrf");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfLessThan(Boolean value) {
            addCriterion("resourceUrl.f_need_csrf <", value, "needCsrf");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfLessThanOrEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_need_csrf <=", value, "needCsrf");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfIn(List<Boolean> values) {
            addCriterion("resourceUrl.f_need_csrf in", values, "needCsrf");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfNotIn(List<Boolean> values) {
            addCriterion("resourceUrl.f_need_csrf not in", values, "needCsrf");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfBetween(Boolean value1, Boolean value2) {
            addCriterion("resourceUrl.f_need_csrf between", value1, value2, "needCsrf");
            return (Criteria) this;
        }

        public Criteria andNeedCsrfNotBetween(Boolean value1, Boolean value2) {
            addCriterion("resourceUrl.f_need_csrf not between", value1, value2, "needCsrf");
            return (Criteria) this;
        }

        public Criteria andOrderIsNull() {
            addCriterion("resourceUrl.f_order is null");
            return (Criteria) this;
        }

        public Criteria andOrderIsNotNull() {
            addCriterion("resourceUrl.f_order is not null");
            return (Criteria) this;
        }

        public Criteria andOrderEqualTo(Integer value) {
            addCriterion("resourceUrl.f_order =", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotEqualTo(Integer value) {
            addCriterion("resourceUrl.f_order <>", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThan(Integer value) {
            addCriterion("resourceUrl.f_order >", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("resourceUrl.f_order >=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThan(Integer value) {
            addCriterion("resourceUrl.f_order <", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThanOrEqualTo(Integer value) {
            addCriterion("resourceUrl.f_order <=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderIn(List<Integer> values) {
            addCriterion("resourceUrl.f_order in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotIn(List<Integer> values) {
            addCriterion("resourceUrl.f_order not in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderBetween(Integer value1, Integer value2) {
            addCriterion("resourceUrl.f_order between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("resourceUrl.f_order not between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIsNull() {
            addCriterion("resourceUrl.f_sys_add_time is null");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIsNotNull() {
            addCriterion("resourceUrl.f_sys_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_add_time =", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_add_time <>", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeGreaterThan(Date value) {
            addCriterion("resourceUrl.f_sys_add_time >", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_add_time >=", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeLessThan(Date value) {
            addCriterion("resourceUrl.f_sys_add_time <", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_add_time <=", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIn(List<Date> values) {
            addCriterion("resourceUrl.f_sys_add_time in", values, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotIn(List<Date> values) {
            addCriterion("resourceUrl.f_sys_add_time not in", values, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeBetween(Date value1, Date value2) {
            addCriterion("resourceUrl.f_sys_add_time between", value1, value2, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("resourceUrl.f_sys_add_time not between", value1, value2, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeIsNull() {
            addCriterion("resourceUrl.f_sys_upd_time is null");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeIsNotNull() {
            addCriterion("resourceUrl.f_sys_upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_upd_time =", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeNotEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_upd_time <>", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeGreaterThan(Date value) {
            addCriterion("resourceUrl.f_sys_upd_time >", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_upd_time >=", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeLessThan(Date value) {
            addCriterion("resourceUrl.f_sys_upd_time <", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_upd_time <=", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeIn(List<Date> values) {
            addCriterion("resourceUrl.f_sys_upd_time in", values, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeNotIn(List<Date> values) {
            addCriterion("resourceUrl.f_sys_upd_time not in", values, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeBetween(Date value1, Date value2) {
            addCriterion("resourceUrl.f_sys_upd_time between", value1, value2, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("resourceUrl.f_sys_upd_time not between", value1, value2, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeIsNull() {
            addCriterion("resourceUrl.f_sys_del_time is null");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeIsNotNull() {
            addCriterion("resourceUrl.f_sys_del_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_del_time =", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeNotEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_del_time <>", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeGreaterThan(Date value) {
            addCriterion("resourceUrl.f_sys_del_time >", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_del_time >=", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeLessThan(Date value) {
            addCriterion("resourceUrl.f_sys_del_time <", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeLessThanOrEqualTo(Date value) {
            addCriterion("resourceUrl.f_sys_del_time <=", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeIn(List<Date> values) {
            addCriterion("resourceUrl.f_sys_del_time in", values, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeNotIn(List<Date> values) {
            addCriterion("resourceUrl.f_sys_del_time not in", values, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeBetween(Date value1, Date value2) {
            addCriterion("resourceUrl.f_sys_del_time between", value1, value2, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeNotBetween(Date value1, Date value2) {
            addCriterion("resourceUrl.f_sys_del_time not between", value1, value2, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysAddUserIsNull() {
            addCriterion("resourceUrl.f_sys_add_user is null");
            return (Criteria) this;
        }

        public Criteria andSysAddUserIsNotNull() {
            addCriterion("resourceUrl.f_sys_add_user is not null");
            return (Criteria) this;
        }

        public Criteria andSysAddUserEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_add_user =", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserNotEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_add_user <>", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserGreaterThan(String value) {
            addCriterion("resourceUrl.f_sys_add_user >", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserGreaterThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_add_user >=", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserLessThan(String value) {
            addCriterion("resourceUrl.f_sys_add_user <", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserLessThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_add_user <=", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserLike(String value) {
            addCriterion("resourceUrl.f_sys_add_user like", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserNotLike(String value) {
            addCriterion("resourceUrl.f_sys_add_user not like", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserIn(List<String> values) {
            addCriterion("resourceUrl.f_sys_add_user in", values, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserNotIn(List<String> values) {
            addCriterion("resourceUrl.f_sys_add_user not in", values, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_sys_add_user between", value1, value2, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserNotBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_sys_add_user not between", value1, value2, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserIsNull() {
            addCriterion("resourceUrl.f_sys_upd_user is null");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserIsNotNull() {
            addCriterion("resourceUrl.f_sys_upd_user is not null");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_upd_user =", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserNotEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_upd_user <>", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserGreaterThan(String value) {
            addCriterion("resourceUrl.f_sys_upd_user >", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserGreaterThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_upd_user >=", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserLessThan(String value) {
            addCriterion("resourceUrl.f_sys_upd_user <", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserLessThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_upd_user <=", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserLike(String value) {
            addCriterion("resourceUrl.f_sys_upd_user like", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserNotLike(String value) {
            addCriterion("resourceUrl.f_sys_upd_user not like", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserIn(List<String> values) {
            addCriterion("resourceUrl.f_sys_upd_user in", values, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserNotIn(List<String> values) {
            addCriterion("resourceUrl.f_sys_upd_user not in", values, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_sys_upd_user between", value1, value2, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserNotBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_sys_upd_user not between", value1, value2, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserIsNull() {
            addCriterion("resourceUrl.f_sys_del_user is null");
            return (Criteria) this;
        }

        public Criteria andSysDelUserIsNotNull() {
            addCriterion("resourceUrl.f_sys_del_user is not null");
            return (Criteria) this;
        }

        public Criteria andSysDelUserEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_del_user =", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserNotEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_del_user <>", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserGreaterThan(String value) {
            addCriterion("resourceUrl.f_sys_del_user >", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserGreaterThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_del_user >=", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserLessThan(String value) {
            addCriterion("resourceUrl.f_sys_del_user <", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserLessThanOrEqualTo(String value) {
            addCriterion("resourceUrl.f_sys_del_user <=", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserLike(String value) {
            addCriterion("resourceUrl.f_sys_del_user like", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserNotLike(String value) {
            addCriterion("resourceUrl.f_sys_del_user not like", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserIn(List<String> values) {
            addCriterion("resourceUrl.f_sys_del_user in", values, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserNotIn(List<String> values) {
            addCriterion("resourceUrl.f_sys_del_user not in", values, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_sys_del_user between", value1, value2, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserNotBetween(String value1, String value2) {
            addCriterion("resourceUrl.f_sys_del_user not between", value1, value2, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelStateIsNull() {
            addCriterion("resourceUrl.f_sys_del_state is null");
            return (Criteria) this;
        }

        public Criteria andSysDelStateIsNotNull() {
            addCriterion("resourceUrl.f_sys_del_state is not null");
            return (Criteria) this;
        }

        public Criteria andSysDelStateEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_sys_del_state =", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateNotEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_sys_del_state <>", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateGreaterThan(Boolean value) {
            addCriterion("resourceUrl.f_sys_del_state >", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_sys_del_state >=", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateLessThan(Boolean value) {
            addCriterion("resourceUrl.f_sys_del_state <", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateLessThanOrEqualTo(Boolean value) {
            addCriterion("resourceUrl.f_sys_del_state <=", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateIn(List<Boolean> values) {
            addCriterion("resourceUrl.f_sys_del_state in", values, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateNotIn(List<Boolean> values) {
            addCriterion("resourceUrl.f_sys_del_state not in", values, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateBetween(Boolean value1, Boolean value2) {
            addCriterion("resourceUrl.f_sys_del_state between", value1, value2, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("resourceUrl.f_sys_del_state not between", value1, value2, "sysDelState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_resource_url
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resource_url
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeleted(boolean deleted) {
            return deleted ? andSysDelStateEqualTo(ResourceUrl.DEL_FLAG_OFF) : andSysDelStateNotEqualTo(ResourceUrl.DEL_FLAG_OFF);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_resource_url
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}