package org.prcode.business.basedomain.roleResource.domain;

import java.io.Serializable;
import org.prcode.basedomain.base.BaseDomain;

public class RoleResource extends BaseDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.f_id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.f_role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.f_resource_url_id
     *
     * @mbg.generated
     */
    private String resourceUrlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role_resource
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.f_id
     *
     * @return the value of t_role_resource.f_id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.f_id
     *
     * @param id the value for t_role_resource.f_id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.f_role_id
     *
     * @return the value of t_role_resource.f_role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.f_role_id
     *
     * @param roleId the value for t_role_resource.f_role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.f_resource_url_id
     *
     * @return the value of t_role_resource.f_resource_url_id
     *
     * @mbg.generated
     */
    public String getResourceUrlId() {
        return resourceUrlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.f_resource_url_id
     *
     * @param resourceUrlId the value for t_role_resource.f_resource_url_id
     *
     * @mbg.generated
     */
    public void setResourceUrlId(String resourceUrlId) {
        this.resourceUrlId = resourceUrlId == null ? null : resourceUrlId.trim();
    }
}