package org.prcode.log.basedomain.oosLogger.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OosLoggerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    public OosLoggerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("oosLogger.f_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("oosLogger.f_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("oosLogger.f_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("oosLogger.f_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("oosLogger.f_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("oosLogger.f_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("oosLogger.f_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("oosLogger.f_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("oosLogger.f_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("oosLogger.f_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("oosLogger.f_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("oosLogger.f_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeIsNull() {
            addCriterion("oosLogger.f_req_start_time is null");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeIsNotNull() {
            addCriterion("oosLogger.f_req_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeEqualTo(Date value) {
            addCriterion("oosLogger.f_req_start_time =", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeNotEqualTo(Date value) {
            addCriterion("oosLogger.f_req_start_time <>", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeGreaterThan(Date value) {
            addCriterion("oosLogger.f_req_start_time >", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("oosLogger.f_req_start_time >=", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeLessThan(Date value) {
            addCriterion("oosLogger.f_req_start_time <", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("oosLogger.f_req_start_time <=", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeIn(List<Date> values) {
            addCriterion("oosLogger.f_req_start_time in", values, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeNotIn(List<Date> values) {
            addCriterion("oosLogger.f_req_start_time not in", values, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeBetween(Date value1, Date value2) {
            addCriterion("oosLogger.f_req_start_time between", value1, value2, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("oosLogger.f_req_start_time not between", value1, value2, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("oosLogger.f_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("oosLogger.f_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("oosLogger.f_user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("oosLogger.f_user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("oosLogger.f_user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("oosLogger.f_user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("oosLogger.f_user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("oosLogger.f_user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("oosLogger.f_user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("oosLogger.f_user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("oosLogger.f_user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserAccNoIsNull() {
            addCriterion("oosLogger.f_user_acc_no is null");
            return (Criteria) this;
        }

        public Criteria andUserAccNoIsNotNull() {
            addCriterion("oosLogger.f_user_acc_no is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccNoEqualTo(String value) {
            addCriterion("oosLogger.f_user_acc_no =", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoNotEqualTo(String value) {
            addCriterion("oosLogger.f_user_acc_no <>", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoGreaterThan(String value) {
            addCriterion("oosLogger.f_user_acc_no >", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_user_acc_no >=", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoLessThan(String value) {
            addCriterion("oosLogger.f_user_acc_no <", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_user_acc_no <=", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoLike(String value) {
            addCriterion("oosLogger.f_user_acc_no like", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoNotLike(String value) {
            addCriterion("oosLogger.f_user_acc_no not like", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoIn(List<String> values) {
            addCriterion("oosLogger.f_user_acc_no in", values, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoNotIn(List<String> values) {
            addCriterion("oosLogger.f_user_acc_no not in", values, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoBetween(String value1, String value2) {
            addCriterion("oosLogger.f_user_acc_no between", value1, value2, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_user_acc_no not between", value1, value2, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeIsNull() {
            addCriterion("oosLogger.f_user_acc_type is null");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeIsNotNull() {
            addCriterion("oosLogger.f_user_acc_type is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeEqualTo(Byte value) {
            addCriterion("oosLogger.f_user_acc_type =", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeNotEqualTo(Byte value) {
            addCriterion("oosLogger.f_user_acc_type <>", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeGreaterThan(Byte value) {
            addCriterion("oosLogger.f_user_acc_type >", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("oosLogger.f_user_acc_type >=", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeLessThan(Byte value) {
            addCriterion("oosLogger.f_user_acc_type <", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeLessThanOrEqualTo(Byte value) {
            addCriterion("oosLogger.f_user_acc_type <=", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeIn(List<Byte> values) {
            addCriterion("oosLogger.f_user_acc_type in", values, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeNotIn(List<Byte> values) {
            addCriterion("oosLogger.f_user_acc_type not in", values, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeBetween(Byte value1, Byte value2) {
            addCriterion("oosLogger.f_user_acc_type between", value1, value2, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("oosLogger.f_user_acc_type not between", value1, value2, "userAccType");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailIsNull() {
            addCriterion("oosLogger.f_action_url_tail is null");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailIsNotNull() {
            addCriterion("oosLogger.f_action_url_tail is not null");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailEqualTo(String value) {
            addCriterion("oosLogger.f_action_url_tail =", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailNotEqualTo(String value) {
            addCriterion("oosLogger.f_action_url_tail <>", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailGreaterThan(String value) {
            addCriterion("oosLogger.f_action_url_tail >", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_action_url_tail >=", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailLessThan(String value) {
            addCriterion("oosLogger.f_action_url_tail <", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_action_url_tail <=", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailLike(String value) {
            addCriterion("oosLogger.f_action_url_tail like", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailNotLike(String value) {
            addCriterion("oosLogger.f_action_url_tail not like", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailIn(List<String> values) {
            addCriterion("oosLogger.f_action_url_tail in", values, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailNotIn(List<String> values) {
            addCriterion("oosLogger.f_action_url_tail not in", values, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailBetween(String value1, String value2) {
            addCriterion("oosLogger.f_action_url_tail between", value1, value2, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_action_url_tail not between", value1, value2, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllIsNull() {
            addCriterion("oosLogger.f_action_url_all is null");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllIsNotNull() {
            addCriterion("oosLogger.f_action_url_all is not null");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllEqualTo(String value) {
            addCriterion("oosLogger.f_action_url_all =", value, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllNotEqualTo(String value) {
            addCriterion("oosLogger.f_action_url_all <>", value, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllGreaterThan(String value) {
            addCriterion("oosLogger.f_action_url_all >", value, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_action_url_all >=", value, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllLessThan(String value) {
            addCriterion("oosLogger.f_action_url_all <", value, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_action_url_all <=", value, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllLike(String value) {
            addCriterion("oosLogger.f_action_url_all like", value, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllNotLike(String value) {
            addCriterion("oosLogger.f_action_url_all not like", value, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllIn(List<String> values) {
            addCriterion("oosLogger.f_action_url_all in", values, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllNotIn(List<String> values) {
            addCriterion("oosLogger.f_action_url_all not in", values, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllBetween(String value1, String value2) {
            addCriterion("oosLogger.f_action_url_all between", value1, value2, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionUrlAllNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_action_url_all not between", value1, value2, "actionUrlAll");
            return (Criteria) this;
        }

        public Criteria andActionResCodeIsNull() {
            addCriterion("oosLogger.f_action_res_code is null");
            return (Criteria) this;
        }

        public Criteria andActionResCodeIsNotNull() {
            addCriterion("oosLogger.f_action_res_code is not null");
            return (Criteria) this;
        }

        public Criteria andActionResCodeEqualTo(String value) {
            addCriterion("oosLogger.f_action_res_code =", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeNotEqualTo(String value) {
            addCriterion("oosLogger.f_action_res_code <>", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeGreaterThan(String value) {
            addCriterion("oosLogger.f_action_res_code >", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_action_res_code >=", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeLessThan(String value) {
            addCriterion("oosLogger.f_action_res_code <", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_action_res_code <=", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeLike(String value) {
            addCriterion("oosLogger.f_action_res_code like", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeNotLike(String value) {
            addCriterion("oosLogger.f_action_res_code not like", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeIn(List<String> values) {
            addCriterion("oosLogger.f_action_res_code in", values, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeNotIn(List<String> values) {
            addCriterion("oosLogger.f_action_res_code not in", values, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeBetween(String value1, String value2) {
            addCriterion("oosLogger.f_action_res_code between", value1, value2, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_action_res_code not between", value1, value2, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionIsNull() {
            addCriterion("oosLogger.f_is_undefined_exception is null");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionIsNotNull() {
            addCriterion("oosLogger.f_is_undefined_exception is not null");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionEqualTo(Boolean value) {
            addCriterion("oosLogger.f_is_undefined_exception =", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionNotEqualTo(Boolean value) {
            addCriterion("oosLogger.f_is_undefined_exception <>", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionGreaterThan(Boolean value) {
            addCriterion("oosLogger.f_is_undefined_exception >", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionGreaterThanOrEqualTo(Boolean value) {
            addCriterion("oosLogger.f_is_undefined_exception >=", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionLessThan(Boolean value) {
            addCriterion("oosLogger.f_is_undefined_exception <", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionLessThanOrEqualTo(Boolean value) {
            addCriterion("oosLogger.f_is_undefined_exception <=", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionIn(List<Boolean> values) {
            addCriterion("oosLogger.f_is_undefined_exception in", values, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionNotIn(List<Boolean> values) {
            addCriterion("oosLogger.f_is_undefined_exception not in", values, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionBetween(Boolean value1, Boolean value2) {
            addCriterion("oosLogger.f_is_undefined_exception between", value1, value2, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionNotBetween(Boolean value1, Boolean value2) {
            addCriterion("oosLogger.f_is_undefined_exception not between", value1, value2, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("oosLogger.f_ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("oosLogger.f_ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("oosLogger.f_ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("oosLogger.f_ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("oosLogger.f_ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("oosLogger.f_ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("oosLogger.f_ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("oosLogger.f_ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("oosLogger.f_ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("oosLogger.f_ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("oosLogger.f_ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("oosLogger.f_device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("oosLogger.f_device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(String value) {
            addCriterion("oosLogger.f_device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(String value) {
            addCriterion("oosLogger.f_device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(String value) {
            addCriterion("oosLogger.f_device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(String value) {
            addCriterion("oosLogger.f_device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLike(String value) {
            addCriterion("oosLogger.f_device_id like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotLike(String value) {
            addCriterion("oosLogger.f_device_id not like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<String> values) {
            addCriterion("oosLogger.f_device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<String> values) {
            addCriterion("oosLogger.f_device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(String value1, String value2) {
            addCriterion("oosLogger.f_device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andOsIsNull() {
            addCriterion("oosLogger.f_os is null");
            return (Criteria) this;
        }

        public Criteria andOsIsNotNull() {
            addCriterion("oosLogger.f_os is not null");
            return (Criteria) this;
        }

        public Criteria andOsEqualTo(String value) {
            addCriterion("oosLogger.f_os =", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotEqualTo(String value) {
            addCriterion("oosLogger.f_os <>", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsGreaterThan(String value) {
            addCriterion("oosLogger.f_os >", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_os >=", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLessThan(String value) {
            addCriterion("oosLogger.f_os <", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_os <=", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLike(String value) {
            addCriterion("oosLogger.f_os like", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotLike(String value) {
            addCriterion("oosLogger.f_os not like", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsIn(List<String> values) {
            addCriterion("oosLogger.f_os in", values, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotIn(List<String> values) {
            addCriterion("oosLogger.f_os not in", values, "os");
            return (Criteria) this;
        }

        public Criteria andOsBetween(String value1, String value2) {
            addCriterion("oosLogger.f_os between", value1, value2, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_os not between", value1, value2, "os");
            return (Criteria) this;
        }

        public Criteria andOsVersionIsNull() {
            addCriterion("oosLogger.f_os_version is null");
            return (Criteria) this;
        }

        public Criteria andOsVersionIsNotNull() {
            addCriterion("oosLogger.f_os_version is not null");
            return (Criteria) this;
        }

        public Criteria andOsVersionEqualTo(String value) {
            addCriterion("oosLogger.f_os_version =", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotEqualTo(String value) {
            addCriterion("oosLogger.f_os_version <>", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionGreaterThan(String value) {
            addCriterion("oosLogger.f_os_version >", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_os_version >=", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLessThan(String value) {
            addCriterion("oosLogger.f_os_version <", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_os_version <=", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLike(String value) {
            addCriterion("oosLogger.f_os_version like", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotLike(String value) {
            addCriterion("oosLogger.f_os_version not like", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionIn(List<String> values) {
            addCriterion("oosLogger.f_os_version in", values, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotIn(List<String> values) {
            addCriterion("oosLogger.f_os_version not in", values, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionBetween(String value1, String value2) {
            addCriterion("oosLogger.f_os_version between", value1, value2, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_os_version not between", value1, value2, "osVersion");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeIsNull() {
            addCriterion("oosLogger.f_req_deal_time is null");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeIsNotNull() {
            addCriterion("oosLogger.f_req_deal_time is not null");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeEqualTo(Integer value) {
            addCriterion("oosLogger.f_req_deal_time =", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeNotEqualTo(Integer value) {
            addCriterion("oosLogger.f_req_deal_time <>", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeGreaterThan(Integer value) {
            addCriterion("oosLogger.f_req_deal_time >", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("oosLogger.f_req_deal_time >=", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeLessThan(Integer value) {
            addCriterion("oosLogger.f_req_deal_time <", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeLessThanOrEqualTo(Integer value) {
            addCriterion("oosLogger.f_req_deal_time <=", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeIn(List<Integer> values) {
            addCriterion("oosLogger.f_req_deal_time in", values, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeNotIn(List<Integer> values) {
            addCriterion("oosLogger.f_req_deal_time not in", values, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeBetween(Integer value1, Integer value2) {
            addCriterion("oosLogger.f_req_deal_time between", value1, value2, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("oosLogger.f_req_deal_time not between", value1, value2, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIsNull() {
            addCriterion("oosLogger.f_req_end_time is null");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIsNotNull() {
            addCriterion("oosLogger.f_req_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeEqualTo(Date value) {
            addCriterion("oosLogger.f_req_end_time =", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotEqualTo(Date value) {
            addCriterion("oosLogger.f_req_end_time <>", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeGreaterThan(Date value) {
            addCriterion("oosLogger.f_req_end_time >", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("oosLogger.f_req_end_time >=", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeLessThan(Date value) {
            addCriterion("oosLogger.f_req_end_time <", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("oosLogger.f_req_end_time <=", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIn(List<Date> values) {
            addCriterion("oosLogger.f_req_end_time in", values, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotIn(List<Date> values) {
            addCriterion("oosLogger.f_req_end_time not in", values, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeBetween(Date value1, Date value2) {
            addCriterion("oosLogger.f_req_end_time between", value1, value2, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("oosLogger.f_req_end_time not between", value1, value2, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIsNull() {
            addCriterion("oosLogger.f_sys_add_time is null");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIsNotNull() {
            addCriterion("oosLogger.f_sys_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_add_time =", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_add_time <>", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeGreaterThan(Date value) {
            addCriterion("oosLogger.f_sys_add_time >", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_add_time >=", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeLessThan(Date value) {
            addCriterion("oosLogger.f_sys_add_time <", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_add_time <=", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIn(List<Date> values) {
            addCriterion("oosLogger.f_sys_add_time in", values, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotIn(List<Date> values) {
            addCriterion("oosLogger.f_sys_add_time not in", values, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeBetween(Date value1, Date value2) {
            addCriterion("oosLogger.f_sys_add_time between", value1, value2, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("oosLogger.f_sys_add_time not between", value1, value2, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeIsNull() {
            addCriterion("oosLogger.f_sys_upd_time is null");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeIsNotNull() {
            addCriterion("oosLogger.f_sys_upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_upd_time =", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeNotEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_upd_time <>", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeGreaterThan(Date value) {
            addCriterion("oosLogger.f_sys_upd_time >", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_upd_time >=", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeLessThan(Date value) {
            addCriterion("oosLogger.f_sys_upd_time <", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_upd_time <=", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeIn(List<Date> values) {
            addCriterion("oosLogger.f_sys_upd_time in", values, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeNotIn(List<Date> values) {
            addCriterion("oosLogger.f_sys_upd_time not in", values, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeBetween(Date value1, Date value2) {
            addCriterion("oosLogger.f_sys_upd_time between", value1, value2, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("oosLogger.f_sys_upd_time not between", value1, value2, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeIsNull() {
            addCriterion("oosLogger.f_sys_del_time is null");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeIsNotNull() {
            addCriterion("oosLogger.f_sys_del_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_del_time =", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeNotEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_del_time <>", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeGreaterThan(Date value) {
            addCriterion("oosLogger.f_sys_del_time >", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_del_time >=", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeLessThan(Date value) {
            addCriterion("oosLogger.f_sys_del_time <", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeLessThanOrEqualTo(Date value) {
            addCriterion("oosLogger.f_sys_del_time <=", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeIn(List<Date> values) {
            addCriterion("oosLogger.f_sys_del_time in", values, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeNotIn(List<Date> values) {
            addCriterion("oosLogger.f_sys_del_time not in", values, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeBetween(Date value1, Date value2) {
            addCriterion("oosLogger.f_sys_del_time between", value1, value2, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeNotBetween(Date value1, Date value2) {
            addCriterion("oosLogger.f_sys_del_time not between", value1, value2, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysAddUserIsNull() {
            addCriterion("oosLogger.f_sys_add_user is null");
            return (Criteria) this;
        }

        public Criteria andSysAddUserIsNotNull() {
            addCriterion("oosLogger.f_sys_add_user is not null");
            return (Criteria) this;
        }

        public Criteria andSysAddUserEqualTo(String value) {
            addCriterion("oosLogger.f_sys_add_user =", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserNotEqualTo(String value) {
            addCriterion("oosLogger.f_sys_add_user <>", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserGreaterThan(String value) {
            addCriterion("oosLogger.f_sys_add_user >", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_sys_add_user >=", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserLessThan(String value) {
            addCriterion("oosLogger.f_sys_add_user <", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_sys_add_user <=", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserLike(String value) {
            addCriterion("oosLogger.f_sys_add_user like", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserNotLike(String value) {
            addCriterion("oosLogger.f_sys_add_user not like", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserIn(List<String> values) {
            addCriterion("oosLogger.f_sys_add_user in", values, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserNotIn(List<String> values) {
            addCriterion("oosLogger.f_sys_add_user not in", values, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserBetween(String value1, String value2) {
            addCriterion("oosLogger.f_sys_add_user between", value1, value2, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_sys_add_user not between", value1, value2, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserIsNull() {
            addCriterion("oosLogger.f_sys_upd_user is null");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserIsNotNull() {
            addCriterion("oosLogger.f_sys_upd_user is not null");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserEqualTo(String value) {
            addCriterion("oosLogger.f_sys_upd_user =", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserNotEqualTo(String value) {
            addCriterion("oosLogger.f_sys_upd_user <>", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserGreaterThan(String value) {
            addCriterion("oosLogger.f_sys_upd_user >", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_sys_upd_user >=", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserLessThan(String value) {
            addCriterion("oosLogger.f_sys_upd_user <", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_sys_upd_user <=", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserLike(String value) {
            addCriterion("oosLogger.f_sys_upd_user like", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserNotLike(String value) {
            addCriterion("oosLogger.f_sys_upd_user not like", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserIn(List<String> values) {
            addCriterion("oosLogger.f_sys_upd_user in", values, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserNotIn(List<String> values) {
            addCriterion("oosLogger.f_sys_upd_user not in", values, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserBetween(String value1, String value2) {
            addCriterion("oosLogger.f_sys_upd_user between", value1, value2, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_sys_upd_user not between", value1, value2, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserIsNull() {
            addCriterion("oosLogger.f_sys_del_user is null");
            return (Criteria) this;
        }

        public Criteria andSysDelUserIsNotNull() {
            addCriterion("oosLogger.f_sys_del_user is not null");
            return (Criteria) this;
        }

        public Criteria andSysDelUserEqualTo(String value) {
            addCriterion("oosLogger.f_sys_del_user =", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserNotEqualTo(String value) {
            addCriterion("oosLogger.f_sys_del_user <>", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserGreaterThan(String value) {
            addCriterion("oosLogger.f_sys_del_user >", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserGreaterThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_sys_del_user >=", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserLessThan(String value) {
            addCriterion("oosLogger.f_sys_del_user <", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserLessThanOrEqualTo(String value) {
            addCriterion("oosLogger.f_sys_del_user <=", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserLike(String value) {
            addCriterion("oosLogger.f_sys_del_user like", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserNotLike(String value) {
            addCriterion("oosLogger.f_sys_del_user not like", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserIn(List<String> values) {
            addCriterion("oosLogger.f_sys_del_user in", values, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserNotIn(List<String> values) {
            addCriterion("oosLogger.f_sys_del_user not in", values, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserBetween(String value1, String value2) {
            addCriterion("oosLogger.f_sys_del_user between", value1, value2, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserNotBetween(String value1, String value2) {
            addCriterion("oosLogger.f_sys_del_user not between", value1, value2, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelStateIsNull() {
            addCriterion("oosLogger.f_sys_del_state is null");
            return (Criteria) this;
        }

        public Criteria andSysDelStateIsNotNull() {
            addCriterion("oosLogger.f_sys_del_state is not null");
            return (Criteria) this;
        }

        public Criteria andSysDelStateEqualTo(Boolean value) {
            addCriterion("oosLogger.f_sys_del_state =", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateNotEqualTo(Boolean value) {
            addCriterion("oosLogger.f_sys_del_state <>", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateGreaterThan(Boolean value) {
            addCriterion("oosLogger.f_sys_del_state >", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("oosLogger.f_sys_del_state >=", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateLessThan(Boolean value) {
            addCriterion("oosLogger.f_sys_del_state <", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateLessThanOrEqualTo(Boolean value) {
            addCriterion("oosLogger.f_sys_del_state <=", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateIn(List<Boolean> values) {
            addCriterion("oosLogger.f_sys_del_state in", values, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateNotIn(List<Boolean> values) {
            addCriterion("oosLogger.f_sys_del_state not in", values, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateBetween(Boolean value1, Boolean value2) {
            addCriterion("oosLogger.f_sys_del_state between", value1, value2, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("oosLogger.f_sys_del_state not between", value1, value2, "sysDelState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_oos_logger
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_oos_logger
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}