package org.prcode.business.basedomain.loginNo.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoginNoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public LoginNoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("loginNo.f_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("loginNo.f_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("loginNo.f_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("loginNo.f_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("loginNo.f_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("loginNo.f_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("loginNo.f_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("loginNo.f_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("loginNo.f_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("loginNo.f_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("loginNo.f_user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("loginNo.f_user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("loginNo.f_user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("loginNo.f_user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("loginNo.f_user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("loginNo.f_user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserAccountIsNull() {
            addCriterion("loginNo.f_user_account is null");
            return (Criteria) this;
        }

        public Criteria andUserAccountIsNotNull() {
            addCriterion("loginNo.f_user_account is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccountEqualTo(String value) {
            addCriterion("loginNo.f_user_account =", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotEqualTo(String value) {
            addCriterion("loginNo.f_user_account <>", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountGreaterThan(String value) {
            addCriterion("loginNo.f_user_account >", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountGreaterThanOrEqualTo(String value) {
            addCriterion("loginNo.f_user_account >=", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLessThan(String value) {
            addCriterion("loginNo.f_user_account <", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLessThanOrEqualTo(String value) {
            addCriterion("loginNo.f_user_account <=", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLike(String value) {
            addCriterion("loginNo.f_user_account like", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotLike(String value) {
            addCriterion("loginNo.f_user_account not like", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountIn(List<String> values) {
            addCriterion("loginNo.f_user_account in", values, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotIn(List<String> values) {
            addCriterion("loginNo.f_user_account not in", values, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountBetween(String value1, String value2) {
            addCriterion("loginNo.f_user_account between", value1, value2, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotBetween(String value1, String value2) {
            addCriterion("loginNo.f_user_account not between", value1, value2, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserPwdIsNull() {
            addCriterion("loginNo.f_user_pwd is null");
            return (Criteria) this;
        }

        public Criteria andUserPwdIsNotNull() {
            addCriterion("loginNo.f_user_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andUserPwdEqualTo(String value) {
            addCriterion("loginNo.f_user_pwd =", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotEqualTo(String value) {
            addCriterion("loginNo.f_user_pwd <>", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdGreaterThan(String value) {
            addCriterion("loginNo.f_user_pwd >", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdGreaterThanOrEqualTo(String value) {
            addCriterion("loginNo.f_user_pwd >=", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdLessThan(String value) {
            addCriterion("loginNo.f_user_pwd <", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdLessThanOrEqualTo(String value) {
            addCriterion("loginNo.f_user_pwd <=", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdLike(String value) {
            addCriterion("loginNo.f_user_pwd like", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotLike(String value) {
            addCriterion("loginNo.f_user_pwd not like", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdIn(List<String> values) {
            addCriterion("loginNo.f_user_pwd in", values, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotIn(List<String> values) {
            addCriterion("loginNo.f_user_pwd not in", values, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdBetween(String value1, String value2) {
            addCriterion("loginNo.f_user_pwd between", value1, value2, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotBetween(String value1, String value2) {
            addCriterion("loginNo.f_user_pwd not between", value1, value2, "userPwd");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("loginNo.f_type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("loginNo.f_type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("loginNo.f_type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("loginNo.f_type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("loginNo.f_type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("loginNo.f_type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("loginNo.f_type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("loginNo.f_type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("loginNo.f_type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("loginNo.f_type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("loginNo.f_type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("loginNo.f_type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdIsNull() {
            addCriterion("loginNo.f_wechat_union_id is null");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdIsNotNull() {
            addCriterion("loginNo.f_wechat_union_id is not null");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdEqualTo(String value) {
            addCriterion("loginNo.f_wechat_union_id =", value, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdNotEqualTo(String value) {
            addCriterion("loginNo.f_wechat_union_id <>", value, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdGreaterThan(String value) {
            addCriterion("loginNo.f_wechat_union_id >", value, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdGreaterThanOrEqualTo(String value) {
            addCriterion("loginNo.f_wechat_union_id >=", value, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdLessThan(String value) {
            addCriterion("loginNo.f_wechat_union_id <", value, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdLessThanOrEqualTo(String value) {
            addCriterion("loginNo.f_wechat_union_id <=", value, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdLike(String value) {
            addCriterion("loginNo.f_wechat_union_id like", value, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdNotLike(String value) {
            addCriterion("loginNo.f_wechat_union_id not like", value, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdIn(List<String> values) {
            addCriterion("loginNo.f_wechat_union_id in", values, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdNotIn(List<String> values) {
            addCriterion("loginNo.f_wechat_union_id not in", values, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdBetween(String value1, String value2) {
            addCriterion("loginNo.f_wechat_union_id between", value1, value2, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andWechatUnionIdNotBetween(String value1, String value2) {
            addCriterion("loginNo.f_wechat_union_id not between", value1, value2, "wechatUnionId");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIsNull() {
            addCriterion("loginNo.f_sys_add_time is null");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIsNotNull() {
            addCriterion("loginNo.f_sys_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeEqualTo(Date value) {
            addCriterion("loginNo.f_sys_add_time =", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotEqualTo(Date value) {
            addCriterion("loginNo.f_sys_add_time <>", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeGreaterThan(Date value) {
            addCriterion("loginNo.f_sys_add_time >", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys_add_time >=", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeLessThan(Date value) {
            addCriterion("loginNo.f_sys_add_time <", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys_add_time <=", value, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeIn(List<Date> values) {
            addCriterion("loginNo.f_sys_add_time in", values, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotIn(List<Date> values) {
            addCriterion("loginNo.f_sys_add_time not in", values, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys_add_time between", value1, value2, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys_add_time not between", value1, value2, "sysAddTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeIsNull() {
            addCriterion("loginNo.f_sys_upd_time is null");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeIsNotNull() {
            addCriterion("loginNo.f_sys_upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeEqualTo(Date value) {
            addCriterion("loginNo.f_sys_upd_time =", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeNotEqualTo(Date value) {
            addCriterion("loginNo.f_sys_upd_time <>", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeGreaterThan(Date value) {
            addCriterion("loginNo.f_sys_upd_time >", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys_upd_time >=", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeLessThan(Date value) {
            addCriterion("loginNo.f_sys_upd_time <", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys_upd_time <=", value, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeIn(List<Date> values) {
            addCriterion("loginNo.f_sys_upd_time in", values, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeNotIn(List<Date> values) {
            addCriterion("loginNo.f_sys_upd_time not in", values, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys_upd_time between", value1, value2, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys_upd_time not between", value1, value2, "sysUpdTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeIsNull() {
            addCriterion("loginNo.f_sys_del_time is null");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeIsNotNull() {
            addCriterion("loginNo.f_sys_del_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeEqualTo(Date value) {
            addCriterion("loginNo.f_sys_del_time =", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeNotEqualTo(Date value) {
            addCriterion("loginNo.f_sys_del_time <>", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeGreaterThan(Date value) {
            addCriterion("loginNo.f_sys_del_time >", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys_del_time >=", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeLessThan(Date value) {
            addCriterion("loginNo.f_sys_del_time <", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeLessThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys_del_time <=", value, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeIn(List<Date> values) {
            addCriterion("loginNo.f_sys_del_time in", values, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeNotIn(List<Date> values) {
            addCriterion("loginNo.f_sys_del_time not in", values, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys_del_time between", value1, value2, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysDelTimeNotBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys_del_time not between", value1, value2, "sysDelTime");
            return (Criteria) this;
        }

        public Criteria andSysAddUserIsNull() {
            addCriterion("loginNo.f_sys_add_user is null");
            return (Criteria) this;
        }

        public Criteria andSysAddUserIsNotNull() {
            addCriterion("loginNo.f_sys_add_user is not null");
            return (Criteria) this;
        }

        public Criteria andSysAddUserEqualTo(Long value) {
            addCriterion("loginNo.f_sys_add_user =", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserNotEqualTo(Long value) {
            addCriterion("loginNo.f_sys_add_user <>", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserGreaterThan(Long value) {
            addCriterion("loginNo.f_sys_add_user >", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserGreaterThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys_add_user >=", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserLessThan(Long value) {
            addCriterion("loginNo.f_sys_add_user <", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserLessThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys_add_user <=", value, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserIn(List<Long> values) {
            addCriterion("loginNo.f_sys_add_user in", values, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserNotIn(List<Long> values) {
            addCriterion("loginNo.f_sys_add_user not in", values, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys_add_user between", value1, value2, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysAddUserNotBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys_add_user not between", value1, value2, "sysAddUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserIsNull() {
            addCriterion("loginNo.f_sys_upd_user is null");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserIsNotNull() {
            addCriterion("loginNo.f_sys_upd_user is not null");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserEqualTo(Long value) {
            addCriterion("loginNo.f_sys_upd_user =", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserNotEqualTo(Long value) {
            addCriterion("loginNo.f_sys_upd_user <>", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserGreaterThan(Long value) {
            addCriterion("loginNo.f_sys_upd_user >", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserGreaterThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys_upd_user >=", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserLessThan(Long value) {
            addCriterion("loginNo.f_sys_upd_user <", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserLessThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys_upd_user <=", value, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserIn(List<Long> values) {
            addCriterion("loginNo.f_sys_upd_user in", values, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserNotIn(List<Long> values) {
            addCriterion("loginNo.f_sys_upd_user not in", values, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys_upd_user between", value1, value2, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysUpdUserNotBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys_upd_user not between", value1, value2, "sysUpdUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserIsNull() {
            addCriterion("loginNo.f_sys_del_user is null");
            return (Criteria) this;
        }

        public Criteria andSysDelUserIsNotNull() {
            addCriterion("loginNo.f_sys_del_user is not null");
            return (Criteria) this;
        }

        public Criteria andSysDelUserEqualTo(Long value) {
            addCriterion("loginNo.f_sys_del_user =", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserNotEqualTo(Long value) {
            addCriterion("loginNo.f_sys_del_user <>", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserGreaterThan(Long value) {
            addCriterion("loginNo.f_sys_del_user >", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserGreaterThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys_del_user >=", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserLessThan(Long value) {
            addCriterion("loginNo.f_sys_del_user <", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserLessThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys_del_user <=", value, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserIn(List<Long> values) {
            addCriterion("loginNo.f_sys_del_user in", values, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserNotIn(List<Long> values) {
            addCriterion("loginNo.f_sys_del_user not in", values, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys_del_user between", value1, value2, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelUserNotBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys_del_user not between", value1, value2, "sysDelUser");
            return (Criteria) this;
        }

        public Criteria andSysDelStateIsNull() {
            addCriterion("loginNo.f_sys_del_state is null");
            return (Criteria) this;
        }

        public Criteria andSysDelStateIsNotNull() {
            addCriterion("loginNo.f_sys_del_state is not null");
            return (Criteria) this;
        }

        public Criteria andSysDelStateEqualTo(Boolean value) {
            addCriterion("loginNo.f_sys_del_state =", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateNotEqualTo(Boolean value) {
            addCriterion("loginNo.f_sys_del_state <>", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateGreaterThan(Boolean value) {
            addCriterion("loginNo.f_sys_del_state >", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("loginNo.f_sys_del_state >=", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateLessThan(Boolean value) {
            addCriterion("loginNo.f_sys_del_state <", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateLessThanOrEqualTo(Boolean value) {
            addCriterion("loginNo.f_sys_del_state <=", value, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateIn(List<Boolean> values) {
            addCriterion("loginNo.f_sys_del_state in", values, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateNotIn(List<Boolean> values) {
            addCriterion("loginNo.f_sys_del_state not in", values, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateBetween(Boolean value1, Boolean value2) {
            addCriterion("loginNo.f_sys_del_state between", value1, value2, "sysDelState");
            return (Criteria) this;
        }

        public Criteria andSysDelStateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("loginNo.f_sys_del_state not between", value1, value2, "sysDelState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_login_no
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_login_no
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeleted(boolean deleted) {
            return deleted ? andSysDelStateEqualTo(LoginNo.DEL_FLAG_OFF) : andSysDelStateNotEqualTo(LoginNo.DEL_FLAG_OFF);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}