package org.prcode.business.basedomain.loginNo.domain;

import java.io.Serializable;
import org.prcode.basedomain.base.BaseDomain;

public class LoginNo extends BaseDomain implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_no
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DEL_FLAG_ON = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_no
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean DEL_FLAG_OFF = true;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_no
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    @Deprecated
    public static final Boolean DEL_FLAG = DEL_FLAG_OFF;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_user_account
     *
     * @mbg.generated
     */
    private String userAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_user_pwd
     *
     * @mbg.generated
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_wechat_union_id
     *
     * @mbg.generated
     */
    private String wechatUnionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_id
     *
     * @return the value of t_login_no.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_id
     *
     * @param id the value for t_login_no.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_user_id
     *
     * @return the value of t_login_no.f_user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_user_id
     *
     * @param userId the value for t_login_no.f_user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_user_account
     *
     * @return the value of t_login_no.f_user_account
     *
     * @mbg.generated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_user_account
     *
     * @param userAccount the value for t_login_no.f_user_account
     *
     * @mbg.generated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_user_pwd
     *
     * @return the value of t_login_no.f_user_pwd
     *
     * @mbg.generated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_user_pwd
     *
     * @param userPwd the value for t_login_no.f_user_pwd
     *
     * @mbg.generated
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_type
     *
     * @return the value of t_login_no.f_type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_type
     *
     * @param type the value for t_login_no.f_type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_wechat_union_id
     *
     * @return the value of t_login_no.f_wechat_union_id
     *
     * @mbg.generated
     */
    public String getWechatUnionId() {
        return wechatUnionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_wechat_union_id
     *
     * @param wechatUnionId the value for t_login_no.f_wechat_union_id
     *
     * @mbg.generated
     */
    public void setWechatUnionId(String wechatUnionId) {
        this.wechatUnionId = wechatUnionId == null ? null : wechatUnionId.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_login_no
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("f_id"),
        userId("f_user_id"),
        userAccount("f_user_account"),
        userPwd("f_user_pwd"),
        type("f_type"),
        wechatUnionId("f_wechat_union_id"),
        sysAddTime("f_sys_add_time"),
        sysUpdTime("f_sys_upd_time"),
        sysDelTime("f_sys_del_time"),
        sysAddUser("f_sys_add_user"),
        sysUpdUser("f_sys_upd_user"),
        sysDelUser("f_sys_del_user"),
        sysDelState("f_sys_del_state");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_login_no
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_login_no
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_login_no
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_login_no
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_login_no
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_login_no
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}